require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdventureGamesController do

  # This should return the minimal set of attributes required to create a valid
  # AdventureGame. As you add validations to AdventureGame, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "new" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdventureGamesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all adventure_games as @adventure_games" do
      adventure_game = AdventureGame.create! valid_attributes
      get :index, {}, valid_session
      assigns(:adventure_games).should eq([adventure_game])
    end
  end

  describe "GET show" do
    it "assigns the requested adventure_game as @adventure_game" do
      adventure_game = AdventureGame.create! valid_attributes
      get :show, {:id => adventure_game.to_param}, valid_session
      assigns(:adventure_game).should eq(adventure_game)
    end
  end

  describe "GET new" do
    it "assigns a new adventure_game as @adventure_game" do
      get :new, {}, valid_session
      assigns(:adventure_game).should be_a_new(AdventureGame)
    end
  end

  describe "GET edit" do
    it "assigns the requested adventure_game as @adventure_game" do
      adventure_game = AdventureGame.create! valid_attributes
      get :edit, {:id => adventure_game.to_param}, valid_session
      assigns(:adventure_game).should eq(adventure_game)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdventureGame" do
        expect {
          post :create, {:adventure_game => valid_attributes}, valid_session
        }.to change(AdventureGame, :count).by(1)
      end

      it "assigns a newly created adventure_game as @adventure_game" do
        post :create, {:adventure_game => valid_attributes}, valid_session
        assigns(:adventure_game).should be_a(AdventureGame)
        assigns(:adventure_game).should be_persisted
      end

      it "redirects to the created adventure_game" do
        post :create, {:adventure_game => valid_attributes}, valid_session
        response.should redirect_to(AdventureGame.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved adventure_game as @adventure_game" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdventureGame.any_instance.stub(:save).and_return(false)
        post :create, {:adventure_game => { "new" => "invalid value" }}, valid_session
        assigns(:adventure_game).should be_a_new(AdventureGame)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdventureGame.any_instance.stub(:save).and_return(false)
        post :create, {:adventure_game => { "new" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested adventure_game" do
        adventure_game = AdventureGame.create! valid_attributes
        # Assuming there are no other adventure_games in the database, this
        # specifies that the AdventureGame created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AdventureGame.any_instance.should_receive(:update).with({ "new" => "MyString" })
        put :update, {:id => adventure_game.to_param, :adventure_game => { "new" => "MyString" }}, valid_session
      end

      it "assigns the requested adventure_game as @adventure_game" do
        adventure_game = AdventureGame.create! valid_attributes
        put :update, {:id => adventure_game.to_param, :adventure_game => valid_attributes}, valid_session
        assigns(:adventure_game).should eq(adventure_game)
      end

      it "redirects to the adventure_game" do
        adventure_game = AdventureGame.create! valid_attributes
        put :update, {:id => adventure_game.to_param, :adventure_game => valid_attributes}, valid_session
        response.should redirect_to(adventure_game)
      end
    end

    describe "with invalid params" do
      it "assigns the adventure_game as @adventure_game" do
        adventure_game = AdventureGame.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdventureGame.any_instance.stub(:save).and_return(false)
        put :update, {:id => adventure_game.to_param, :adventure_game => { "new" => "invalid value" }}, valid_session
        assigns(:adventure_game).should eq(adventure_game)
      end

      it "re-renders the 'edit' template" do
        adventure_game = AdventureGame.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdventureGame.any_instance.stub(:save).and_return(false)
        put :update, {:id => adventure_game.to_param, :adventure_game => { "new" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested adventure_game" do
      adventure_game = AdventureGame.create! valid_attributes
      expect {
        delete :destroy, {:id => adventure_game.to_param}, valid_session
      }.to change(AdventureGame, :count).by(-1)
    end

    it "redirects to the adventure_games list" do
      adventure_game = AdventureGame.create! valid_attributes
      delete :destroy, {:id => adventure_game.to_param}, valid_session
      response.should redirect_to(adventure_games_url)
    end
  end

end
